"""Currency lists
   
   If you want to add new supported currency, just add currency 'code' to
   a 'CURRENCY_CODE' table, 'bytecode' to a 'CURRENCY_BYTECODE' table,
   'name' to a 'CURRENCY_NAME' table(at the end of table). It will change all
   associated functions(help, etc.)
"""

CURRENCY_CODE = ["ALL", "AFN", "ARS", "AWG", "AUD", "AZN", "BSD", "BBD", "BYN",
                 "BZD", "BMD", "BOB", "BAM", "BWP", "BGN", "BRL", "BND", "KHR",
                 "CAD", "KYD", "CLP", "CNY", "COP", "CRC", "HRK", "CUP", "CZK",
                 "DKK", "DOP", "XCD", "EGP", "SVC", "EUR", "FKP", "FJD", "GHS",
                 "GIP", "GTQ", "GGP", "GYD", "HNL", "HKD", "HUF", "ISK", "INR",
                 "IDR", "IRR", "IMP", "ILS", "JMD", "JPY", "JEP", "KZT", "KPW",
                 "KRW", "KGS", "LAK", "LBP", "LRD", "MKD", "MYR", "MUR", "MXN",
                 "MNT", "MZN", "NAD", "NPR", "ANG", "NZD", "NIO", "NGN", "NOK",
                 "OMR", "PKR", "PAB", "PYG", "PEN", "PHP", "PLN", "QAR", "RON",
                 "RUB", "SHP", "SAR", "RSD", "SCR", "SGD", "SBD", "SOS", "ZAR",
                 "LKR", "SEK", "CHF", "SRD", "SYP", "TWD", "THB", "TTD", "TRY",
                 "TVD", "UAH", "GBP", "USD", "UYU", "UZS", "VEF", "VND", "YER",
                 "ZWD"]

# Some are(UTF-8 does not understand), some not(utf-8 knows)
CURRENCY_BYTECODE = [b'Lek', b'\xd8\x8b', b'$', b'\xc6\x92', b'$', 
             b'\xd0\xbc\xd0\xb0\xd0\xbd', b'$', b'$', b'Br', b'BZ$', b'$', 
             b'$b', b'KAM', b'P', b'\xd0\xbb\xd0\xb2', b'R$', b'$', 
             b'\xe1\x9f\x9b', b'$', b'$', b'$', b'\xc2\xa5', b'$',
             b'\xe2\x82\xa1', b'kn', b'\xe2\x82\xb1', b'K\xc4\x8d',
             b'kr', b'RD$', b'$', b'\xc2\xa3', b'$', b'\xe2\x82\xac',
             b'\xc2\xa3', b'$', b'\xc2\xa2', b'\xc2\xa3', b'Q',
             b'\xc2\xa3', b'$', b'L', b'$', b'Ft', b'kr', b'', b'Rp',
             b'\xef\xb7\xbc', b'\xc2\xa3', b'\xe2\x82\xaa',
             b'\x4a\x24', b'\xc2\xa5', b'\xc2\xa3',
             b'\xd0\xbb\xd2\xb2', b'\xe2\x82\xa9', b'\xe2\x82\xa9',
             b'\xd0\xbb\xd2\xb2', b'\xe2\x82\xad', b'\xc2\xa3', b'$',
             b'\xd0\xb4\xd0\xb5\xd0\xbd', b'RM', b'\xe2\x82\xa8', b'$',
             b'\xe2\x82\xae', b'MT', b'$', b'\xe2\x82\xa8', b'\xc6\x92',
             b'$', b'C$', b'\xe2\x82\xa6', b'kr', b'\xef\xb7\xbc', 
             b'\xe2\x82\xa8', b'B/.', b'Gs', b'S/.', b'\xe2\x82\xb1',
             b'\x7a\xc5\x82', b'\xef\xb7\xbc', b'lei', b'\xe2\x82\xbd',
             b'\xc2\xa3', b'\xef\xb7\xbc', b'\xd0\x94\xd0\xb8\xd0\xbd\x2e',
             b'\xe2\x82\xa8', b'$', b'$', b'S', b'R', b'\xe2\x82\xa8',
             b'kr', b'CHF', b'$', b'\xc2\xa3', b'NT$', b'\xe0\xb8\xbf',
             b'TT$', b'', b'$',	b'\xe2\x82\xb4', b'\xc2\xa3', b'$',
             b'$U', b'\xd0\xbb\xd0\xb2', b'Bs', b'\xe2\x82\xab',
             b'\xef\xb7\xbc', b'Z$']

CURRENCY_NAME = ["Albania Lek", "Afghanistan Afghani", "Argentina Peso",
                 "Aruba Guilder", "Australia Dollar", "Azerbaijan New Manat",
                 "Bahamas Dollar","Barbados Dollar","Belarus Ruble",
                 "Belize Dollar", "Bermuda Dollar", "Bolivia Boliviano",
                 "Bosnia and Herzegovina Convertible Marka","Botswana Pula",
                 "Bulgaria Lev", "Brazil Real", "Brunei Darussalam Dollar",
                 "Cambodia Riel", "Canada Dollar", "Cayman Islands Dollar",
                 "Chile Peso", "China Yuan Renminbi","Colombia Peso",
                 "Costa Rica Colon", "Croatia Kuna", "Cuba Peso", 
                 "Czech Republic Koruna","Denmark Krone", 
                 "Dominican Republic Peso","East Caribbean Dollar", 
                 "Egypt Pound", "El Salvador Colon",
                 "Euro Member Countries", "Falkland Islands (Malvinas) Pound",
                 "Fiji Dollar", "Ghana Cedi", "Gibraltar Pound",
                 "Guatemala Quetzal", "Guernsey Pound", "Guyana Dollar",
                 "Honduras Lempira", "Hong Kong Dollar", "Hungary Forint",
                 "Iceland Krona", "India Rupee", "Indonesia Rupiah",
                 "Iran Rial", "Isle of Man Pound", "Israel Shekel",
                 "Jamaica Dollar", "Japan Yen", "Jersey Pound",
                 "Kazakhstan Tenge", "Korea (North) Won", "Korea (South) Won",
                 "Kyrgyzstan Som", "Laos Kip", "Lebanon Pound",
                 "Liberia Dollar", "Macedonia Denar", "Malaysia Ringgit",
                 "Mauritius Rupee", "Mexico Peso", "Mongolia Tughrik",
                 "Mozambique Metical", "Namibia Dollar", "Nepal Rupee",
                 "Netherlands Antilles Guilder", "New Zealand Dollar",
                 "Nicaragua Cordoba", "Nigeria Naira", "Norway Krone",
                 "Oman Rial", "Pakistan Rupee", "Panama Balboa",
                 "Paraguay Guarani", "Peru Sol", "Philippines Peso",
                 "Poland Zloty", "Qatar Riyal", "Romania New Leu",
                 "Russia Ruble", "Saint Helena Pound", "Saudi Arabia Riyal",
                 "Serbia Dinar", "Seychelles Rupee", "Singapore Dollar",
                 "Solomon Islands Dollar", "Somalia Shilling",
                 "South Africa Rand", "Sri Lanka Rupee", "Sweden Krona",
                 "Switzerland Franc", "Suriname Dollar", "Syria Pound",
                 "Taiwan New Dollar", "Thailand Baht",
                 "Trinidad and Tobago Dollar", "Turkey Lira", "Tuvalu Dollar",	 
                 "Ukraine Hryvnia", "United Kingdom Pound", 
                 "United States Dollar", "Uruguay Peso", "Uzbekistan Som",
                 "Venezuela Bolivar", "Viet Nam Dong", "Yemen Rial",
                 "Zimbabwe Dollar"]
